import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { fiefAuth } from '@/fief'  // (1)!
import Header from '@/components/Header/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const userinfo = await fiefAuth.getUserInfo() // (2)!
  return (
      <html lang="en">
        <body className={inter.className}>
          <Header userinfo={userinfo} />  {/* (3)! */}
          {children}
        </body>
      </html>
  )
}
